/**
 * Claim scalar fields for Add Column picker (synced from claim-list base columns).
 * Merged into ClaimListAdditionalColumns.getAllColumns().
 */
export const CLAIM_ENTITY_FIELD_COLUMNS: Array<{
  key: string;
  label: string;
  category: string;
  dataType: string;
}> = [
    { key: 'createdDate', label: 'Date Created', category: 'Audit', dataType: 'date' },
    { key: 'modifiedDate', label: 'Modified Date', category: 'Audit', dataType: 'date' },
    { key: 'claTotalChargeTRIG', label: 'Total Charge', category: 'Financial', dataType: 'currency' },
    { key: 'claTotalBalanceCC', label: 'Total Balance', category: 'Financial', dataType: 'currency' },
    { key: 'claFirstDateTRIG', label: '1st DOS', category: 'Financial', dataType: 'date' },
    { key: 'claLastDateTRIG', label: 'Last DOS', category: 'Financial', dataType: 'date' },
    { key: 'claLastUserName', label: 'Modified User', category: 'Audit', dataType: 'string' },
    { key: 'claPatFID', label: 'Patient ID', category: 'Other', dataType: 'number' },
    { key: 'claAttendingPhyFID', label: 'Attending Physician ID', category: 'Physicians', dataType: 'number' },
    { key: 'claBillingPhyFID', label: 'Billing Physician ID', category: 'Physicians', dataType: 'number' },
    { key: 'claReferringPhyFID', label: 'Referring Physician ID', category: 'Physicians', dataType: 'number' },
    { key: 'claCreatedUserGUID', label: 'Created User GUID', category: 'Audit', dataType: 'string' },
    { key: 'claLastUserGUID', label: 'Last User GUID', category: 'Audit', dataType: 'string' },
    { key: 'claCreatedUserName', label: 'Created User Name', category: 'Audit', dataType: 'string' },
    { key: 'claCreatedComputerName', label: 'Created Computer Name', category: 'Audit', dataType: 'string' },
    { key: 'claLastComputerName', label: 'Last Computer Name', category: 'Audit', dataType: 'string' },
    { key: 'claAccidentDate', label: 'Accident Date', category: 'Dates', dataType: 'date' },
    { key: 'claAcuteManifestationDate', label: 'Acute Manifestation Date', category: 'Dates', dataType: 'date' },
    { key: 'claAdmittedDate', label: 'Admitted Date', category: 'Dates', dataType: 'date' },
    { key: 'claAssumedCareDate', label: 'Assumed Care Date', category: 'Dates', dataType: 'date' },
    { key: 'claAuthorizedReturnToWorkDate', label: 'Authorized Return To Work Date', category: 'Dates', dataType: 'date' },
    { key: 'claBox10dClaimCodes', label: 'Box 10d Claim Codes', category: 'Other', dataType: 'string' },
    { key: 'claBox11bOtherClaimIDQualifier', label: 'Box 11b Other Claim ID Qualifier', category: 'Other', dataType: 'string' },
    { key: 'claBox22CodeOverride', label: 'Box 22 Code Override', category: 'Other', dataType: 'string' },
    { key: 'claBox33bOverride', label: 'Box 33b Override', category: 'Other', dataType: 'string' },
    { key: 'claCLIANumber', label: 'CLIA Number', category: 'Other', dataType: 'string' },
    { key: 'claCMNCertOnFile', label: 'CMN Cert On File', category: 'Other', dataType: 'string' },
    { key: 'claCMNCertTypeCode', label: 'CMN Cert Type Code', category: 'Other', dataType: 'string' },
    { key: 'claCMNFormIdentificationCode', label: 'CMN Form Identification Code', category: 'Other', dataType: 'string' },
    { key: 'claCMNInitialDate', label: 'CMN Initial Date', category: 'Dates', dataType: 'date' },
    { key: 'claCMNLengthOfNeed', label: 'CMN Length Of Need', category: 'Other', dataType: 'number' },
    { key: 'claCMNRevisedDate', label: 'CMN Revised Date', category: 'Dates', dataType: 'date' },
    { key: 'claCMNSignedDate', label: 'CMN Signed Date', category: 'Dates', dataType: 'date' },
    { key: 'claCN1Segment', label: 'CN1 Segment', category: 'Other', dataType: 'string' },
    { key: 'claCustomField1', label: 'Custom Field 1', category: 'Custom', dataType: 'string' },
    { key: 'claCustomField2', label: 'Custom Field 2', category: 'Custom', dataType: 'string' },
    { key: 'claCustomField3', label: 'Custom Field 3', category: 'Custom', dataType: 'string' },
    { key: 'claCustomField4', label: 'Custom Field 4', category: 'Custom', dataType: 'string' },
    { key: 'claCustomField5', label: 'Custom Field 5', category: 'Custom', dataType: 'string' },
    { key: 'claDateLastSeen', label: 'Date Last Seen', category: 'Dates', dataType: 'date' },
    { key: 'claDateOfCurrent', label: 'Date Of Current', category: 'Dates', dataType: 'date' },
    { key: 'claDateTotalFrom', label: 'Date Total From', category: 'Dates', dataType: 'date' },
    { key: 'claDateTotalThrough', label: 'Date Total Through', category: 'Dates', dataType: 'date' },
    { key: 'claDelayCode', label: 'Delay Code', category: 'Other', dataType: 'string' },
    { key: 'claDiagnosisCodesCC', label: 'Diagnosis Codes CC', category: 'Clinical', dataType: 'string' },
    { key: 'claDisabilityBeginDate', label: 'Disability Begin Date', category: 'Dates', dataType: 'date' },
    { key: 'claDisabilityEndDate', label: 'Disability End Date', category: 'Dates', dataType: 'date' },
    { key: 'claDischargedDate', label: 'Discharged Date', category: 'Financial', dataType: 'currency' },
    { key: 'claDischargedHour', label: 'Discharged Hour', category: 'Financial', dataType: 'currency' },
    { key: 'claDMEFormData', label: 'DME Form Data', category: 'Clinical', dataType: 'string' },
    { key: 'claEPSDTReferral', label: 'EPSDT Referral', category: 'Other', dataType: 'string' },
    { key: 'claExternalFID', label: 'External FID', category: 'Other', dataType: 'number' },
    { key: 'claFacilityPhyFID', label: 'Facility Physician ID', category: 'Physicians', dataType: 'number' },
    { key: 'claFirstDateOfInjury', label: 'First Date Of Injury', category: 'Dates', dataType: 'date' },
    { key: 'claFirstInsPaymentDateTRIG', label: 'First Ins Payment Date TRIG', category: 'Financial', dataType: 'date' },
    { key: 'claHearingAndPrescriptionDate', label: 'Hearing And Prescription Date', category: 'Dates', dataType: 'date' },
    { key: 'claHomeboundInd', label: 'Homebound Ind', category: 'Other', dataType: 'string' },
    { key: 'claHospiceInd', label: 'Hospice Ind', category: 'Other', dataType: 'string' },
    { key: 'claICDIndicator', label: 'ICD Indicator', category: 'Clinical', dataType: 'string' },
    { key: 'claIDENumber', label: 'IDE Number', category: 'Other', dataType: 'string' },
    { key: 'claInitialTreatmentDate', label: 'Initial Treatment Date', category: 'Dates', dataType: 'date' },
    { key: 'claIgnoreAppliedAmount', label: 'Ignore Applied Amount', category: 'Financial', dataType: 'currency' },
    { key: 'claInsuranceTypeCodeOverride', label: 'Insurance Type Code Override', category: 'Other', dataType: 'string' },
    { key: 'claK3FileInformation', label: 'K3 File Information', category: 'Other', dataType: 'string' },
    { key: 'claLabCharges', label: 'Lab Charges', category: 'Financial', dataType: 'currency' },
    { key: 'claLastMenstrualDate', label: 'Last Menstrual Date', category: 'Dates', dataType: 'date' },
    { key: 'claLastPrintedDate', label: 'Last Printed Date', category: 'Dates', dataType: 'date' },
    { key: 'claLastWorkedDate', label: 'Last Worked Date', category: 'Dates', dataType: 'date' },
    { key: 'claLastXRayDate', label: 'Last X Ray Date', category: 'Dates', dataType: 'date' },
    { key: 'claMammographyCert', label: 'Mammography Cert', category: 'Physicians', dataType: 'string' },
    { key: 'claMedicaidResubmissionCode', label: 'Medicaid Resubmission Code', category: 'EDI', dataType: 'string' },
    { key: 'claMOASegment', label: 'MOA Segment', category: 'Other', dataType: 'string' },
    { key: 'claOperatingPhyFID', label: 'Operating Physician ID', category: 'Physicians', dataType: 'number' },
    { key: 'claOrderingPhyFID', label: 'Ordering Physician ID', category: 'Physicians', dataType: 'number' },
    { key: 'claOutsideLab', label: 'Outside Lab', category: 'Other', dataType: 'number' },
    { key: 'claPaidDateTRIG', label: 'Paid Date TRIG', category: 'Financial', dataType: 'currency' },
    { key: 'claPaperWorkControlNumber', label: 'Paper Work Control Number', category: 'Other', dataType: 'string' },
    { key: 'claPaperWorkInd', label: 'Paper Work Ind', category: 'Other', dataType: 'string' },
    { key: 'claPaperWorkTransmissionCode', label: 'Paper Work Transmission Code', category: 'Other', dataType: 'string' },
    { key: 'claPatientReasonDiagnosis1', label: 'Patient Reason Diagnosis 1', category: 'Clinical', dataType: 'string' },
    { key: 'claPatientReasonDiagnosis2', label: 'Patient Reason Diagnosis 2', category: 'Clinical', dataType: 'string' },
    { key: 'claPatientReasonDiagnosis3', label: 'Patient Reason Diagnosis 3', category: 'Clinical', dataType: 'string' },
    { key: 'claPPSCode', label: 'PPS Code', category: 'Other', dataType: 'string' },
    { key: 'claPricingExceptionCode', label: 'Pricing Exception Code', category: 'Other', dataType: 'string' },
    { key: 'claPrincipalProcedureDate', label: 'Principal Procedure Date', category: 'Dates', dataType: 'date' },
    { key: 'claPrintUnitCharge', label: 'Print Unit Charge', category: 'Financial', dataType: 'currency' },
    { key: 'claProviderAgreementCode', label: 'Provider Agreement Code', category: 'Other', dataType: 'string' },
    { key: 'claRecurUntilDate', label: 'Recur Until Date', category: 'Dates', dataType: 'date' },
    { key: 'claRecurringTimeFrame', label: 'Recurring Time Frame', category: 'Dates', dataType: 'string' },
    { key: 'claReferralNumber', label: 'Referral Number', category: 'Other', dataType: 'string' },
    { key: 'claRelatedTo', label: 'Related To', category: 'Other', dataType: 'string' },
    { key: 'claRelatedToState', label: 'Related To State', category: 'Other', dataType: 'string' },
    { key: 'claRelinquishedCareDate', label: 'Relinquished Care Date', category: 'Dates', dataType: 'date' },
    { key: 'claRenderingPhyFID', label: 'Rendering Physician ID', category: 'Physicians', dataType: 'number' },
    { key: 'claReserved10', label: 'Reserved 10', category: 'Other', dataType: 'string' },
    { key: 'claReserved19', label: 'Reserved 19', category: 'Other', dataType: 'string' },
    { key: 'claSimilarIllnessDate', label: 'Similar Illness Date', category: 'Dates', dataType: 'date' },
    { key: 'claSpecialProgramIndicator', label: 'Special Program Indicator', category: 'Other', dataType: 'string' },
    { key: 'claStatementCoversFromOverride', label: 'Statement Covers From Override', category: 'Billing', dataType: 'string' },
    { key: 'claStatementCoversThroughOverride', label: 'Statement Covers Through Override', category: 'Billing', dataType: 'string' },
    { key: 'claSupervisingPhyFID', label: 'Supervising Physician ID', category: 'Physicians', dataType: 'number' },
    { key: 'claTotalCOAdjTRIG', label: 'Total CO Adj TRIG', category: 'Financial', dataType: 'currency' },
    { key: 'claTotalCRAdjTRIG', label: 'Total CR Adj TRIG', category: 'Financial', dataType: 'currency' },
    { key: 'claTotalOAAdjTRIG', label: 'Total OA Adj TRIG', category: 'Financial', dataType: 'currency' },
    { key: 'claTotalPIAdjTRIG', label: 'Total PI Adj TRIG', category: 'Financial', dataType: 'currency' },
    { key: 'claTotalPRAdjTRIG', label: 'Total PR Adj TRIG', category: 'Financial', dataType: 'currency' },
    { key: 'claTotalServiceLineCountTRIG', label: 'Total Service Line Count TRIG', category: 'Financial', dataType: 'number' },
    { key: 'claTotalInsAmtPaidTRIG', label: 'Total Ins Amt Paid TRIG', category: 'Financial', dataType: 'currency' },
    { key: 'claTotalInsBalanceTRIG', label: 'Total Ins Balance TRIG', category: 'Financial', dataType: 'currency' },
    { key: 'claTotalPatAmtPaidTRIG', label: 'Total Pat Amt Paid TRIG', category: 'Financial', dataType: 'currency' },
    { key: 'claTotalPatBalanceTRIG', label: 'Total Pat Balance TRIG', category: 'Financial', dataType: 'currency' },
    { key: 'claTotalAmtAppliedCC', label: 'Total Amt Applied CC', category: 'Financial', dataType: 'currency' },
    { key: 'billToDisplay', label: 'Bill To Display', category: 'Payers', dataType: 'string' },
];
